### ISSUE TITLE
Renaming ZeroBin Application

### ISSUE THREAD

**Issue by smcgregor** [privly/privly-android#28]
@vshivam,

UX testing on the privly-chrome extension showed confusion on first-use of the system. Part of the problem was that users did not know which application to select and they were not interested in reading about the different apps. This means we needed to select a strong default before asking the users to change applications. In furtherance of "selecting a default," we renamed the ZeroBin application to "Message." This probably means you will need to change a few strings in the Android app to match.

How much work does renaming or introducing an app to privly-android require? I plan on introducing a series of experimental applications in the coming months so I want to workout publishing steps for non-browser interfaces.

-Sean

**Comment by vshivam** [comment]
Renaming Strings doesn't take a lot of work. 

Adding a new application also doesn't take a lot of work. It's as simple as adding a new application directory to the android application and adding the name of that directory to list of available applications. The app then automatically loads application_name/new.html in a webview when selected by the user.

**Comment by vshivam** [comment]
Fixed Here. 

https://github.com/privly/privly-android/pull/36
