### ISSUE TITLE
History page content overflows. 

### ISSUE THREAD

**Issue by vshivam** [privly/privly-android#33]
The width of the content of the History screen doesn't wrap properly.

**Comment by smcgregor** [comment]
This is probably a problem in privly-applications. Can you provide a screen capture and I'll see if I can replicate it on my browser by changing the window dimensions?

**Comment by gitanshu** [comment]
Here are the screenshots: 

![](https://s3.amazonaws.com/pushbullet-uploads/udt5K-FJ0lcj8n7U5XV2tb6dUo3oIBjX3qgLie/Screenshot_2015-02-18-22-37-45.png)

![](https://s3.amazonaws.com/pushbullet-uploads/udt5K-fwhpTTPdAtl3SHiVmjKtZ05gSNFaMXcb/Screenshot_2015-02-18-22-37-50.png)

**Comment by smcgregor** [comment]
I opened the issue on privly-applications. It should not be a difficult fix.

**Comment by smcgregor** [comment]
Fixed in the pull request closed above. Please reopen if the issue persists.

**Comment by gitanshu** [comment]
The content still overflows a bit. Here's a screenie:

![screenshot_2015-03-07-16-44-50](https://cloud.githubusercontent.com/assets/1853790/6541195/a0d152ec-c4e9-11e4-88de-8b992c3dfc93.png)
