### ISSUE TITLE
Update Preference Activity. 

### ISSUE THREAD

**Issue by vshivam** [privly/privly-android#37]
Remove deprecated methods.

@gitanshu A lot of code in the activity which relates to clearing out of session data is commented out. Any ideas why ?

**Comment by gitanshu** [comment]
This is the commit where the new settings activity was added: 
https://github.com/privly/privly-android/commit/2c99fe795e85de7833f116c657e81f5f6406577a
and as the commit message says, something broke the facebook and twitter logout. I wasn't sure of how facebook and twitter sessions are stored and so commented out the code to test other options without crashes. 

The code starting this line: https://github.com/privly/privly-android/blob/gradle-develop/privlyandroid/src/main/java/ly/priv/mobile/SettingsActivityNew.java#L205
is, however, just commented out boilerplate code.

**Comment by vshivam** [comment]
Updated the PreferenceActivity to use a toolbar, made other logout options functional : https://github.com/privly/privly-android/commit/aaa7524826fc7ccdfc2a47daf3e25888e2f72b6e
