### ISSUE TITLE
LobsterTextView. 

### ISSUE THREAD

**Issue by vshivam** [privly/privly-android#38]
It might be a better idea to create a custom text view class which automatically sets the typeface to lobster rather than setting it explicitly to every text view via the java code.

**Comment by vshivam** [comment]
Created a new class here : https://github.com/privly/privly-android/blob/gradle-develop/privlyandroid/src/main/java/ly/priv/mobile/utils/LobsterTextView.java 

The login activity now uses the LobsterTextView. 

TODO: Find other places where could probably use this.

**Comment by arjunvijayvargiya** [comment]
![screenshot_2015-03-06-23-50-40](https://cloud.githubusercontent.com/assets/7685777/6540481/7d1971be-c4c5-11e4-8392-ef1ad6e8dc61.png)

I think we can make the gui better here by adding lobster font at Logout options and change content server

**Comment by gitanshu** [comment]
I am sorry but the screenshot doesn't look good to me. While it might be possible to improve this, in my view, Lobster grabs attention and this doesn't seem like a right place for this. Settings should be kept simple and consistent across apps.

**Comment by vshivam** [comment]
I do agree. I don't think we need the lobster text view here.
