### ISSUE TITLE
Call JSObject Bridge method which redirects users to LoginActivity. 

### ISSUE THREAD

**Issue by vshivam** [privly/privly-android#41]
Whenever there's an authentication failure on loading a PrivlyApplication in the webview, it shows a button to login which loads the 'Login' PrivlyApplication in the WebView because that's the default behaviour for privly-web. This will possibly confuse the user because he sees a different login page on first usage of the application and then a different login screen in the above mentioned case. 

So, what we need to do is to redirect the user to LoginActivity in case of the authentication failure. The method is already defined here : https://github.com/privly/privly-android/blob/master/src/main/java/ly/priv/mobile/utils/JsObject.java#L113

You'd probably want to initiate the call from here : 
https://github.com/privly/privly-applications/blob/1c6a6f586401c0c98f7a3575f7cdf952642b50a3/shared/javascripts/network_service.js#L439

Previous discussion : https://github.com/privly/privly-applications/issues/154

**Comment by arjunvijayvargiya** [comment]
I think the approach would be to:

Android/Java part
1.add a call in the onCreate of the  java file attached to the javascript the following
      webView.addJavascriptInterface(getApplicationContext(), "android"); 
      // The second parameter is the name of the global JavaScript variable which the JavaScript interface object is bound to. 

2.add a method in the same class
 
    @JavascriptInterface
    public void startLoginActivity(String message) {
      Intent i=new Intent(class.this,LoginActivity.java);
    }

javascript part
call this android.startLoginActivity();

**Comment by arjunvijayvargiya** [comment]
I have added    androidJsBridge.showLoginActivity(); in the  showLoggedOutNav: function() of Network_service.js. Now what I am getting is: whenever there's an authentication failure on loading a PrivlyApplication in the web-view, user is directly redirected to LoginActivity directly without showing a small login button in webview which was earlier present .Is this ok ??? To add something to this we can prompt user using toast by adding a toast message like(authentication failure")before redirecting to android loginActivity.java.What do you suggest????

**Comment by vshivam** [comment]
Not sure what you're trying to ask here.

**Comment by arjunvijayvargiya** [comment]
Sorry for not being clear.I just wanted to tell that I have resolved this bug by adding a  call in the 

androidJsBridge.showLoginActivity(); 
in the showLoggedOutNav: function() of Network_service.js.

**Comment by arjunvijayvargiya** [comment]
Can I open a pull request for this in Privly Application???

**Comment by vshivam** [comment]
Sure.

**Comment by arjunvijayvargiya** [comment]
I have updated my earlier pull request with my new commit:https://github.com/arjunvijayvargiya/privly-applications/commit/9a79304686395aabc48fc570df9a2660dc6e76dc 

updated  pull request:https://github.com/privly/privly-applications/pull/213

**Comment by arjunvijayvargiya** [comment]
Hi Shivam,
Updated Network.js .Added platform check before calling the LoginActivity by JSBridge.

https://github.com/arjunvijayvargiya/privly-applications/commit/c64616309d1d89467aab7286cba33c6211f04c2f

**Comment by arjunvijayvargiya** [comment]
Yeah ,should have used already defined function..
https://github.com/arjunvijayvargiya/privly-applications/commit/f3c8afa0e655c4b5fb86d31933df27045941bd6b

**Comment by arjunvijayvargiya** [comment]
Hi shivam,
                 I have put the non android code in the else block.Please check it once on
https://github.com/arjunvijayvargiya/privly-applications/commit/14f32564a674dd250534e90951dbb678d2f853ad

**Comment by smcgregor** [comment]
@vshivam This calls something on the Android side, good? https://github.com/privly/privly-applications/pull/218

**Comment by vshivam** [comment]
Fixed : https://github.com/privly/privly-applications/pull/218
