### ISSUE TITLE
Intent handler for Privly Links. 

### ISSUE THREAD

**Issue by vshivam** [privly/privly-android#43]
The app should be able to handle clicks of Privly links from other places such as the browser.

**Comment by akoul** [comment]
This will probably require adding an intent in androidmanifest.xml file which will receive the content from other applications like browser. Can you tell me the < data android:mimeType > value which is required  so that content from other application can be handled by privly-android app?

**Comment by vshivam** [comment]
I don't think we need the mime type in this case because we're not trying to handle intents of a particular content type. What we're trying to do is to handle URLs of a specific type. So you'll need to work with `android:host` and `android:scheme` attributes of the `intent-filter`.

Since these attributes need to be defined in the manifest and cannot be added dynamically, I think what might make sense is to handle the https://privlyalpha.org and https://dev.privly.org by default. 

Reference : http://developer.android.com/guide/topics/manifest/data-element.html#scheme

**Comment by arjunvijayvargiya** [comment]
Hi Shivam,
                   I have doubt.What if when user has already selected the browser/chrome as default app to open these kind of URLs? It wont show a secondary option to deal with these kind of URLs???

**Comment by vshivam** [comment]
I don't think we can do anything about that. The link will open in the browser directly.

**Comment by akoul** [comment]
I tried including the following code in manifest.xml under <activity android:name=".gui.activities.MainActivity">

 <intent-filter>
                <data android:scheme="*" android:host="*" />
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                </intent-filter>
            <intent-filter>

But that didn't seem to work. 
I also tired including <android:exported="true">, but still in vain. :/

**Comment by vshivam** [comment]
@akoul I can't see any code. Plus, this issue has almost been fixed by @jagatheesan

**Comment by akoul** [comment]
Sorry for that.
How do you upload the code in comments?
Adding <> before the code makes it invisible

**Comment by vshivam** [comment]
Include the code in ``. 

You need to include the `android:host` and `android:scheme` values. Check this out : http://stackoverflow.com/questions/525063/android-respond-to-url-in-intent

**Comment by akoul** [comment]
<intent-filter>
 <data android:scheme="*" android:host="*" /> 
 <action android:name="android.intent.action.VIEW" /> 
 <category android:name="android.intent.category.DEFAULT /> 
 <category android:name="android.intent.category.BROWSABLE /> 
 </intent-filter>

Can u see the code now?

**Comment by akoul** [comment]
I also did the same thing but couldn't make a pull request due to some work. Anyways, nice job @Jagatheesan

**Comment by vshivam** [comment]
Fixed : https://github.com/privly/privly-android/pull/52
