### ISSUE TITLE
Auto-completing the email address at the Login screen

### ISSUE THREAD

**Issue by arjunvijayvargiya** [privly/privly-android#47]
How about auto-completing the email address at the login screen?like remembering the last login address or auto completing the gmail.com in the end.This feature will save some time from the user side?

**Comment by vshivam** [comment]
I am not sure about auto complete. However, text suggestions sound like a good idea.

**Comment by arjunvijayvargiya** [comment]
We don’t know all the email addresses the user could potentially have. What we know however from his phone is all the email addresses he/she used as an account (Google, Facebook, Twitter, …).
This data source can be used to provide completions.We can load the user accounts through the Account class provided by android
As some accounts may not have an email address linked to them, we filter them and keep only the ones who matches an email regex. We also use a Set to remove the duplicates.Then we will bind them to the AutoCompleteTextView through an ArrayAdapter.

It will also remember the user's email address earlier used to log into privly.I have modeled everything in a demo app.Just wanted to know your suggestions

**Comment by vshivam** [comment]
Sounds good. Before you start working on this, make sure you have pulled the latest updates from the develop branch.

**Comment by arjunvijayvargiya** [comment]
Hi shivam,
                 can you send me an invite on this email address: arjun.arvdroid@gmail.com .This will help me in testing the feature

**Comment by arjunvijayvargiya** [comment]
I have implemented that feature on my local .This is the screenshot. I can improve on the design of the drop-down ranging from fonts colors based on the privly theme.

![privly](https://cloud.githubusercontent.com/assets/7685777/6545415/038cca02-c5ac-11e4-83ba-0dae3a523329.png). I can improve on the design of the drop-down including the

**Comment by vshivam** [comment]
Looks good.

**Comment by arjunvijayvargiya** [comment]
can I make a Pull request.

**Comment by vshivam** [comment]
Go ahead.

On Sun, Mar 8, 2015 at 9:15 PM, Arjun Vijayvargiya <notifications@github.com

**Comment by arjunvijayvargiya** [comment]
I have implemented  the above discussed feature.Pull request #49

**Comment by arjunvijayvargiya** [comment]
I have updated based on the changes suggested by you.Pull request #50 .

**Comment by arjunvijayvargiya** [comment]
I have updated based on the changes suggested by you.Pull request #52 .

updates Done
1)Removed extra object of Values class that was emailVal
2)removed old readnewprefs method and created new getters and setters for lastloginemailaddress
3)updated APP_PREFERENCE_NEWPREFS with new name of constant

**Comment by vshivam** [comment]
Resolved : https://github.com/privly/privly-android/pull/52
