### ISSUE TITLE
Authentication Problem

### ISSUE THREAD

**Issue by parthkarkhanis479** [privly/privly-android#65]
The username and password that I used for https://privlyalpha.org/ isn't working for the app

**Comment by vshivam** [comment]
Is there a relevant message in the logs?

-Shivam

**Comment by parthkarkhanis479** [comment]
![image](https://cloud.githubusercontent.com/assets/15124073/13026684/dfdd4fc4-d256-11e5-96f7-84d0f5201f81.png)
String cannot be converted to json objects

**Comment by parthkarkhanis479** [comment]
This what I am getting in response from the server.
 mLoginResponse : <!DOCTYPE html>
                                                  <html>
                                                   <head>
                                                    <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
                                                    
                                                    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
                                                    <link href="../shared/css/common.css" media="screen" rel="stylesheet" type="text/css"/>
                                                    <script src="../vendor/polyfill/es6-promise.js">
                                                    </script>
                                                    <script src="../shared/javascripts/meta_loader.js" type="text/javascript">
                                                    </script>
                                                    <script src="../shared/javascripts/parameters.js" type="text/javascript">
                                                    </script>
                                                    <script src="../shared/javascripts/local_storage.js" type="text/javascript">
                                                    </script>
                                                    <script src="../shared/javascripts/context_messenger.js" type="text/javascript">
                                                    </script>
                                                    <script src="../shared/javascripts/glyph.js" type="text/javascript">
                                                    </script>
                                                    <script src="../shared/javascripts/storage.js" type="text/javascript">
                                                    </script>
                                                    <script src="../shared/javascripts/options.js" type="text/javascript">
                                                    </script>
                                                    <script src="../shared/javascripts/network_service.js" type="text/javascript">
                                                    </script>
                                                    <title>
                                                     New Login
                                                    </title>
                                                    <link class="top" href="../vendor/bootstrap/css/bootstrap.min.css" media="screen" rel="stylesheet"/>
                                                    <link class="top" href="../shared/css/top/top.css" rel="stylesheet"/>
                                                    <script src="../shared/javascripts/event_emitter.js" type="text/javascript">
                                                    </script>
                                                    <script src="../shared/javascripts/viewAdapters/new.js" type="text/javascript">
                                                    </script>
                                                    <script src="../vendor/jquery.min.js" type="text/javascript">
                                                    </script>
                                                    <script src="js/new.js" type="text/javascript">
                                                    </script>
                                                   </head>
                                                   <body data-privly-exclude="true">
                                                    
                                                    <script src="../vendor/bootstrap/js/bootstrap.min.js">
                                                    </script>
                                                    
                                                    <div id="wrap">
                                                     <div class="navbar navbar-inverse navbar-fixed-top injected_hide mobile_hide" role="navigation">
                                                      <div class="container">
                                                       <div class="navbar-header">
                                                        <button class="navbar-toggle" data-target=".navbar-collapse" data-toggle="collapse" type="button">
                                                         <span class="sr-only">
                                                          Toggle navigation
                                                         </span>
                                                         <span class="icon-bar">
                                                         </span>
                                                         <span class="icon-bar">
                                                         </span>
                                                         <span class="icon-bar">
                                                         </span>
                                                        </button>
                                                        <a class="navbar-brand lobster home_domain" href="../Help/content_server.html" title="This is your current content server">
                                                         Privly
                                                        </a>
                                                       </div>
                                                       <div class="collapse navbar-collapse">
                                                        <ul class="nav navbar-nav">
                                                         <li class="logged_in_nav" style="display:none;">
                                                          <a href="../History/new.html">
                                                           <span class="glyphicon glyphicon-list-alt">
                                                           </span>
                                                           History
                                                          </a>
                                                         </li>
                                                         <li class="active logged_out_nav">
                                                          <a class="login_url" href="../Login/new.html">
                                                           <span class="glyphicon glyphicon-log-in">
                                                           </span>
                                                           Login
                                                          </a>
                                                         </li>
                                                         <li class="active dropdown logged_in_nav" style="display:none;">
                                                          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                                           <b class="caret">
                                                           </b>
                                                           New Link
                                                          </a>
                                                          <ul class="dropdown-menu">
                                                           <li class="dropdown-header">
                                                            Select Application
                                                           </li>
                                                           <li>
                                                            <a href="../Message/new.html">
                                                             <span class="glyphicon glyphicon-pencil">
                                                             </span>
                                                             New Message
                                                            </a>
                                                           </li>
                                                           <li>
                                                            <a href="../PlainPost/new.html">
                                                             <span class="glyphicon glyphicon-pencil">
                                                             </span>
                                                             New PlainPost
                                                            </a>
                                                           </li>
                                                           <li>
                                                            <a href="../Help/new.html">
                                                             <span class="glyphicon glyphicon-info-sign">
                                                             </span>
                                                             Help
                                                            </a>
                                                           </li>
                                                          </ul>
                                                         </li>
                                                         <li class
From the above response,I think the issue is from the server side.It's not sending data back in json format due which we are getting this exception

**Comment by vshivam** [comment]
Yeah, I think there's an issue with the server. CCing @smcgregor

**Comment by smcgregor** [comment]
I am not having any issues generating an auth token, but I did recently update the token authentication code. What is the URL of the auth request that you are using? I tested the token auth endpoints here [0] since we exposed these forms for testing purposes a while back.

[0] https://privlyalpha.org/token_authentications/new

**Comment by vshivam** [comment]
The app uses, https://privlyalpha.org/token_authentications.json , with the username and password as POST data. 

[0] https://github.com/privly/privly-android/blob/master/app/src/main/java/ly/priv/mobile/gui/activities/LoginActivity.java#L173

**Comment by mkash32** [comment]
I think the problem is due to the mechanism used by Rails to combat CSRF.
https://github.com/privly/privly-web/blob/master/app/controllers/application_controller.rb#L8
From what I've been reading, the default is to throw an exception when an authenticity_token is not provided. The authenticity_token will only be provided when we send the post request through the form. 
It is suggested to use `protect_from_forgery with: :null_session` for APIs. 
I'm not that familiar with rails but I found this information to be relevant to this problem. (Token generation works fine when sending the post request through the form given in https://privlyalpha.org/token_authentications/new. But sending a post request through postman or the app to https://privlyalpha.org/token_authentications.json isn't working. I noticed when we send the request through the form, the "authenticity_token" parameter is also being sent)

**Comment by smcgregor** [comment]
@mkash32 A plausible if not likely explanation.

@vshivam Do you want me to test removing the authenticity_token from the `/new` endpoint on token authentications?

**Comment by vshivam** [comment]
@smcgregor While the authenticity_token is definitely one of the issues, does it also explain the absence of Set-Cookie header in the response ? If yes, then bypassing the csrf protection might solve the issue.

**Comment by smcgregor** [comment]
I'll experiment with dev.privly.org and let you know.

**Comment by smcgregor** [comment]
@vshivam Can you give it a try with dev.privly.org?

**Comment by mkash32** [comment]
I tried with dev.privly.org, it's working.

**Comment by smcgregor** [comment]
Thanks, @mkash32.

**Comment by parthkarkhanis479** [comment]
@mkash32 I tried replacing the value of DEFAULT_CONTENT_SERVER  as "https://dev.privly.org";
in ConstanValues.java but it still isn't working for me

**Comment by mkash32** [comment]
@parthkarkhanis479 Do you have an account on dev.privly.org?

**Comment by parthkarkhanis479** [comment]
Yes I do have one but with the same id as on privlyalpha.org .But I don't think that should be a problem

**Comment by vshivam** [comment]
@parthkarkhanis479 Make sure you're using the develop branch for building the app locally.

**Comment by mkash32** [comment]
Can you post the response that you received?

**Comment by parthkarkhanis479** [comment]
I am able to log in now but the app shows the following screen.Is that what we are supposed to see after logging in?
![screenshot_2016-02-20-12-50-44](https://cloud.githubusercontent.com/assets/15124073/13195178/39768cba-d7d1-11e5-9235-223fac863a1b.png)

**Comment by smcgregor** [comment]
It looks like you did not specify the --recursive option when you cloned
the repo?

**Comment by vshivam** [comment]
Or you can update the submodule manually[0].

[0] https://github.com/privly/privly-android#developer-info

**Comment by parthkarkhanis479** [comment]
Thnx guys for your help. The app is working properly now.Should I close the issue?

**Comment by vshivam** [comment]
Let's wait for the server side changes to be pushed to https://privlyalpha.org

**Comment by smcgregor** [comment]
I'm just waiting for [TravisCI to run](https://travis-ci.org/smcgregor/privly-web/builds/112134082). Apparently Friday afternoons are not a great time to get free CI. This is taking a while to start.

**Comment by smcgregor** [comment]
Deployed to privlyalpha.org and dev.privly.org. Please comment/reopen if issues persist.
