### ISSUE TITLE
Automatic Log out just after Log in

### ISSUE THREAD

**Issue by mkash32** [privly/privly-android#67]
Since the login isn't working currently, I went to https://privlyalpha.org/token_authentications/new and logged in to get my auth_token and I hard-coded it into the project. After logging into the android app, the privly main page is visible and at the top the status is shown as 

> "Pending Server Check, Application is checking its connection with the remote server" 

This activity is visible for a second and then it goes back to the login activity. The call to log out is being made in the JsObject: https://github.com/privly/privly-android/blob/master/app/src/main/java/ly/priv/mobile/utils/JsObject.java#L115.
This is being called from the javascript code: https://github.com/privly/privly-applications/blob/30b06e77f57eedc451956e318b7ddc5e00877196/shared/javascripts/network_service.js#L447

I'm assuming some checks are being done in the JS code that are redirecting me to log out everytime. Could this be due to harcoding the auth_token?
 
If not, does anyone know why this is happening?

**Comment by vshivam** [comment]
Yes, the JS apps check for a valid auth_token. However, I do not see that being a problem as long as you save the auth_token in Shared Preferences[0]. 

[0] https://github.com/privly/privly-android/blob/develop/app/src/main/java/ly/priv/mobile/gui/activities/LoginActivity.java#L228

**Comment by mkash32** [comment]
The auth_token is saved properly after the login. I started taking a look again and the loginFailure callback in new.js in shared of the privly-applications is being called.

I'm having trouble understanding the control flow of the js code. In [PrivlyApplicationFragment](https://github.com/privly/privly-android/blob/develop/app/src/main/java/ly/priv/mobile/gui/fragments/PrivlyApplicationFragment.java ) we are registering JsObject as the interface for javascript in the webview, and later loading a url and including some js for initialization purposes. But no code seems to be initializing/starting the js code of the privly-applications. I guess I am missing something. My main question is who/where is prompting the loginFailure callback in the js to be called.

**Comment by vshivam** [comment]
The LoginActivity redirects the user to the MainActivity which loads the 'Message' privly application in the webview.

[0] https://github.com/privly/privly-android/blob/develop/app/src/main/java/ly/priv/mobile/gui/activities/MainActivity.java#L85

**Comment by mkash32** [comment]
Yeah I understood that part. The part which is confusing me is the control flow in the javascript code. For example the following is being called in the [js code](https://github.com/privly/privly-applications/blob/30b06e77f57eedc451956e318b7ddc5e00877196/shared/javascripts/network_service.js#L447): ` androidJsBridge.showLoginActivity();`
How did the control flow even reach to that point? And where exactly does the control flow begin in the js code?

**Comment by vshivam** [comment]
It's the 'Message' Privly Application that gets loaded in the fragment, so you need to check the related js code. I'd suggest checking out the `initializeApplication` function in `privly-applications/Message/js/new.js`.

**Comment by mkash32** [comment]
Ok sure, thanks!

**Comment by mkash32** [comment]
I went through new.js in the 'Message' Privly application. I got a better idea of how all of these pieces fit together, thank you for the suggestion.

The auth_token is saved properly and the request made to the server https://github.com/privly/privly-applications/blob/30b06e77f57eedc451956e318b7ddc5e00877196/shared/javascripts/network_service.js#L155 sends the the auth_token as a parameter, but in the response JSON the "signedIn" key has a value of false.

{
	"csrf": "___",
	"burntAfter": "2016-03-20T17:58:17.127+00:00",
	"canPost": false,
	"signedIn": false
}

**Comment by smcgregor** [comment]
Sorry for sending you through these steps. I am hoping the change I just made to dev.privly.org will make these steps unnecessary.

**Comment by mkash32** [comment]
I guess hard-coding the auth_token was the source of the problems. I am using dev.privly.org now and there are no issues.

**Comment by smcgregor** [comment]
Feel free to close this if there is no longer an issue.
